package Core.Window.Input;


public enum KeyCodes {
	Cancel                    ( new int[] {  3    } )                       ,
	 Backspace                 ( new int[] { 8     } )                       , 
	 Tab                       ( new int[] { 9     } )                       ,
	 Enter                     ( new int[] { 10    } )                       ,
	 Clear                     ( new int[] { 12    } )                       ,
	 Shift                     ( new int[] { 16    } )                       ,
	 Ctrl                      ( new int[] { 17    } )                       ,
	 Alt                       ( new int[] { 18    } )                       ,
	 Pause                     ( new int[] { 19    } )                       ,
	 Caps_Lock                 ( new int[] { 20    } )                       , 
	 Kana                      ( new int[] { 21    } )                       ,
	 Final                     ( new int[] { 24    } )                       ,
	 Kanji                     ( new int[] { 25    } )                       ,
	 Escape                    ( new int[] { 27    } )                       ,
	 Convert                   ( new int[] { 28    } )                       ,
	 No_Convert                ( new int[] { 29    } )                       , 
	 Accept                    ( new int[] { 30    } )                       ,
	 Mode_Change               ( new int[] { 31    } )                       , 
	 Space                     ( new int[] { 32    } )                       ,
	 Page_Up                   ( new int[] { 33    } )                       ,
	 Page_Down                 ( new int[] { 34    } )                       , 
	 End                       ( new int[] { 35    } )                       ,
	 Home                      ( new int[] { 36    } )                       ,
	 Up                        ( new int[] { 38,224   } )                    ,
	 Down                      ( new int[] { 40,225   } )                    ,
	 Left                      ( new int[] { 37,226   } )                    ,
	 Right                     ( new int[] { 39,227   } )                    ,
	 Comma                     ( new int[] { 44    } )                       ,
	 Minus                     ( new int[] { 45    } )                       ,
	 Period                    ( new int[] { 46    } )                       ,
	 Slash                     ( new int[] { 47    } )                       ,
	 NUM_0                         ( new int[] { 48    } )                   ,
	 NUM_1                         ( new int[] { 49    } )                   ,
	 NUM_2                         ( new int[] { 50    } )                   ,
	 NUM_3                         ( new int[] { 51    } )                   ,
	 NUM_4                         ( new int[] { 52    } )                   ,
	 NUM_5                         ( new int[] { 53    } )                   ,
	 NUM_6                         ( new int[] { 54    } )                   ,
	 NUM_7                         ( new int[] { 55    } )                   ,
	 NUM_8                         ( new int[] { 56    } )                   ,
	 NUM_9                         ( new int[] { 57    } )                   ,
	 Semicolon                 ( new int[] { 59    } )                       , 
	 Equals                    ( new int[] { 61    } )                       ,
	 A                         ( new int[] { 65    } )                       ,
	 B                         ( new int[] { 66    } )                       ,
	 C                         ( new int[] { 67    } )                       ,
	 D                         ( new int[] { 68    } )                       ,
	 E                         ( new int[] { 69    } )                       ,
	 F                         ( new int[] { 70    } )                       ,
	 G                         ( new int[] { 71    } )                       ,
	 H                         ( new int[] { 72    } )                       ,
	 I                         ( new int[] { 73    } )                       ,
	 J                         ( new int[] { 74    } )                       ,
	 K                         ( new int[] { 75    } )                       ,
	 L                         ( new int[] { 76    } )                       ,
	 M                         ( new int[] { 77    } )                       ,
	 N                         ( new int[] { 78    } )                       ,
	 O                         ( new int[] { 79    } )                       ,
	 P                         ( new int[] { 80    } )                       ,
	 Q                         ( new int[] { 81    } )                       ,
	 R                         ( new int[] { 82    } )                       ,
	 S                         ( new int[] { 83    } )                       ,
	 T                         ( new int[] { 84    } )                       ,
	 U                         ( new int[] { 85    } )                       ,
	 V                         ( new int[] { 86    } )                       ,
	 W                         ( new int[] { 87    } )                       ,
	 X                         ( new int[] { 88    } )                       ,
	 Y                         ( new int[] { 89    } )                       ,
	 Z                         ( new int[] { 90    } )                       ,
	 Open_Bracket              ( new int[] { 91    } )                       , 
	 Back_Slash                ( new int[] { 92    } )                       , 
	 Close_Bracket             ( new int[] { 93    } )                       , 
	 NumPad_0                  ( new int[] { 96    } )                       ,
	 NumPad_1                  ( new int[] { 97    } )                       ,
	 NumPad_2                  ( new int[] { 98    } )                       ,
	 NumPad_3                  ( new int[] { 99    } )                       ,
	 NumPad_4                  ( new int[] { 100   } )                       ,
	 NumPad_5                  ( new int[] { 101   } )                       ,
	 NumPad_6                  ( new int[] { 102   } )                       ,
	 NumPad_7                  ( new int[] { 103   } )                       ,
	 NumPad_8                  ( new int[] { 104   } )                       ,
	 NumPad_9                  ( new int[] { 105   } )                       ,
	 NumPad_Multiply                  ( new int[] { 106   } )                , 
	 NumPad_Plus                  ( new int[] { 107   } )                    , 
	 NumPad_Comma                  ( new int[] { 108   } )                   , 
	 NumPad_Minus                  ( new int[] { 109   } )                   , 
	 NumPad_Dot                  ( new int[] { 110   } )                     , 
	 NumPad_Divide                  ( new int[] { 111   } )                  , 
	 F1                        ( new int[] { 112   } )                       ,
	 F2                        ( new int[] { 113   } )                       ,
	 F3                        ( new int[] { 114   } )                       ,
	 F4                        ( new int[] { 115   } )                       ,
	 F5                        ( new int[] { 116   } )                       ,
	 F6                        ( new int[] { 117   } )                       ,
	 F7                        ( new int[] { 118   } )                       ,
	 F8                        ( new int[] { 119   } )                       ,
	 F9                        ( new int[] { 120   } )                       ,
	 F10                       ( new int[] { 121   } )                       ,
	 F11                       ( new int[] { 122   } )                       ,
	 F12                       ( new int[] { 123   } )                       ,
	 Delete                    ( new int[] { 127   } )                       ,
	 Dead_Grave                ( new int[] { 128   } )                       , 
	 Dead_Acute                ( new int[] { 129   } )                       , 
	 Dead_Circumflex           ( new int[] { 130   } )                       , 
	 Dead_Tilde                ( new int[] { 131   } )                       , 
	 Dead_Macron               ( new int[] { 132   } )                       , 
	 Dead_Breve                ( new int[] { 133   } )                       , 
	 Dead_Above_Dot            ( new int[] { 134   } )                       , 
	 Dead_Diaeresis            ( new int[] { 135   } )                       , 
	 Dead_Above_Ring           ( new int[] { 136   } )                       , 
	 Dead_Double_Acute         ( new int[] { 137   } )                       , 
	 Dead_Caron                ( new int[] { 138   } )                       , 
	 Dead_Cedilla              ( new int[] { 139   } )                       , 
	 Dead_Ogonek               ( new int[] { 140   } )                       , 
	 Dead_Iota                 ( new int[] { 141   } )                       , 
	 Dead_Voiced_Sound         ( new int[] { 142   } )                       , 
	 Dead_Semivoiced_Sound     ( new int[] { 143   } )                       , 
	 Num_Lock                  ( new int[] { 144   } )                       ,
	 Scroll_Lock               ( new int[] { 145   } )                       , 
	 Ampersand                 ( new int[] { 150   } )                       , 
	 Asterisk                  ( new int[] { 151   } )                       ,
	 Double_Quote              ( new int[] { 152   } )                       , 
	 Less                      ( new int[] { 153   } )                       ,
	 Print_Screen              ( new int[] { 154   } )                       , 
	 Insert                    ( new int[] { 155   } )                       ,
	 Help                      ( new int[] { 156   } )                       ,
	 Meta                      ( new int[] { 157   } )                       ,
	 Greater                   ( new int[] { 160   } )                       ,
	 Left_Brace                ( new int[] { 161   } )                       , 
	 Right_Brace               ( new int[] { 162   } )                       , 
	 Back_Quote                ( new int[] { 192   } )                       , 
	 Quote                     ( new int[] { 222   } )                       ,
	 Alphanumeric              ( new int[] { 240   } )                       , 
	 Katakana                  ( new int[] { 241   } )                       ,
	 Hiragana                  ( new int[] { 242   } )                       ,
	 Full_Width                ( new int[] { 243   } )                       , 
	 Half_Width                ( new int[] { 244   } )                       , 
	 Roman_Characters          ( new int[] { 245   } )                       , 
	 All_Candidates            ( new int[] { 256   } )                       , 
	 Previous_Candidate        ( new int[] { 257   } )                       , 
	 Code_Input                ( new int[] { 258   } )                       , 
	 Japanese_Katakana         ( new int[] { 259   } )                       , 
	 Japanese_Hiragana         ( new int[] { 260   } )                       , 
	 Japanese_Roman            ( new int[] { 261   } )                       , 
	 Kana_Lock                 ( new int[] { 262   } )                       , 
	 Input_Method_On_Off       ( new int[] { 263   } )                       , 
	 At                        ( new int[] { 512   } )                       ,
	 Colon                     ( new int[] { 513   } )                       ,
	 Circumflex                ( new int[] { 514   } )                       , 
	 Dollar                    ( new int[] { 515   } )                       ,
	 Euro                      ( new int[] { 516   } )                       ,
	 Exclamation_Mark          ( new int[] { 517   } )                       , 
	 Inverted_Exclamation_Mark ( new int[] { 518   } )                       , 
	 Left_Parenthesis          ( new int[] { 519   } )                       , 
	 Number_Sign               ( new int[] { 520   } )                       , 
	 Plus                      ( new int[] { 521   } )                       ,
	 Right_Parenthesis         ( new int[] { 522   } )                       , 
	 Underscore                ( new int[] { 523   } )                       , 
	 Windows                   ( new int[] { 524   } )                       ,
	 Context_Menu              ( new int[] { 525   } )                       , 
	 F13                       ( new int[] { 61440 } )                       ,
	 F14                       ( new int[] { 61441 } )                       ,
	 F15                       ( new int[] { 61442 } )                       ,
	 F16                       ( new int[] { 61443 } )                       ,
	 F17                       ( new int[] { 61444 } )                       ,
	 F18                       ( new int[] { 61445 } )                       ,
	 F19                       ( new int[] { 61446 } )                       ,
	 F20                       ( new int[] { 61447 } )                       ,
	 F21                       ( new int[] { 61448 } )                       ,
	 F22                       ( new int[] { 61449 } )                       ,
	 F23                       ( new int[] { 61450 } )                       ,
	 F24                       ( new int[] { 61451 } )                       ,
	 Compose                   ( new int[] { 65312 } )                       ,
	 Begin                     ( new int[] { 65368 } )                       ,
	 Alt_Graph                 ( new int[] { 65406 } )                       , 
	 Stop                      ( new int[] { 65480 } )                       ,
	 Again                     ( new int[] { 65481 } )                       ,
	 Props                     ( new int[] { 65482 } )                       ,
	 Undo                      ( new int[] { 65483 } )                       ,
	 Copy                      ( new int[] { 65485 } )                       ,
	 Paste                     ( new int[] { 65487 } )                       ,
	 Find                      ( new int[] { 65488 } )                       ,
	 Cut                       ( new int[] { 65489 } )                       ;
	
	private final int[] key;
	KeyCodes(int[] i) {
		this.key = i;
	}
	public int[] getKeyCodes()
	{
		return this.key;
	}
	public boolean Matchs(int KeyCode)
	{
		for(int x : key) if(KeyCode == x) return true;
		return false;
	}
	public int getKeyCode(int index)
	{
		return this.key[index];
	}
	
}
